processor:
  maxDepth: 176
  ignoreGroupVersions:
    - "GVK"
  ignoreTypes:
    - '\bConfig\b'
    - "CtxValueKey"
    - "Embedded[2-4]$"
    - "ParsedLab"
    - "SetOwnerFuncType"
    - '\bSystem\b'
    - '\bCloudInitNetworkConfig\b'
    - '\bCloudInitNetworkConfigBody\b'
    - '\bNicConfig\b'
    - '\bNicMatcher\b'
  ignoreFields:
    - "status$"
    - "TypeMeta$"
    - "NoUserInput$"
  customMarkers:
    - name: "nodoc"
      target: field
    - name: "hidefromdoc"
      target: type


render:
  kubernetesVersion: 1.25
