---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-knl-kubenetlab-net-v1beta1-knlconfig
  failurePolicy: Fail
  name: mknlconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - knl.kubenetlab.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - knlconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-knl-kubenetlab-net-v1beta1-lab
  failurePolicy: Fail
  name: mlab-v1beta1.kb.io
  rules:
  - apiGroups:
    - knl.kubenetlab.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - labs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-knl-kubenetlab-net-v1beta1-knlconfig
  failurePolicy: Fail
  name: vknlconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - knl.kubenetlab.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - knlconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-knl-kubenetlab-net-v1beta1-lab
  failurePolicy: Fail
  name: vlab-v1beta1.kb.io
  rules:
  - apiGroups:
    - knl.kubenetlab.net
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - labs
  sideEffects: None
