# This rule is not used by the project knl itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to knl.kubenetlab.net resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: knl
    app.kubernetes.io/managed-by: kustomize
  name: lab-viewer-role
rules:
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - labs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - labs/status
  verbs:
  - get
