# This rule is not used by the project knl itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over knl.kubenetlab.net.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: knl
    app.kubernetes.io/managed-by: kustomize
  name: lab-admin-role
rules:
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - labs
  verbs:
  - '*'
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - labs/status
  verbs:
  - get
