---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - knlconfigs
  - labs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - knlconfigs/finalizers
  - labs/finalizers
  verbs:
  - update
- apiGroups:
  - knl.kubenetlab.net
  resources:
  - knlconfigs/status
  - labs/status
  verbs:
  - get
  - patch
  - update
