---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: knlconfigs.knl.kubenetlab.net
spec:
  group: knl.kubenetlab.net
  names:
    kind: KNLConfig
    listKind: KNLConfigList
    plural: knlconfigs
    singular: knlconfig
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: KNLConfig is the Schema for the knlconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of KNLConfig
            properties:
              defaultNode:
                description: defaultNode specifies default values for types of node
                properties:
                  srl:
                    description: |-
                      SRVM *SRVM `json:"srvm,omitempty"`
                      VMPC *VMPC `json:"vpc,omitempty"`
                    nullable: true
                    properties:
                      chassis:
                        type: string
                      image:
                        type: string
                      license:
                        type: string
                    type: object
                type: object
              defaultVxlanDev:
                type: string
              filePass:
                type: string
              fileSvr:
                type: string
              fileUser:
                type: string
              linkMTU:
                type: integer
              sideCarImage:
                type: string
              srCPMLoaderImage:
                type: string
              srIOMLoaderImage:
                type: string
              storageClass:
                type: string
              vxlanDevMap:
                additionalProperties:
                  type: string
                type: object
              vxlanGrp:
                type: string
            type: object
          status:
            description: status defines the observed state of KNLConfig
            properties:
              observedGeneration:
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
