---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: knlconfigs.knl.kubenetlab.net
spec:
  group: knl.kubenetlab.net
  names:
    kind: KNLConfig
    listKind: KNLConfigList
    plural: knlconfigs
    singular: knlconfig
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: KNLConfig is the Schema for the knlconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of KNLConfig
            properties:
              defaultNode:
                description: defaultNode specifies default values for types of node
                properties:
                  pod:
                    description: GeneralPod creates a general pod
                    nullable: true
                    properties:
                      cmd:
                        type: string
                      image:
                        type: string
                      privileged:
                        type: boolean
                    type: object
                  srl:
                    description: |-
                      SRLinux creates a pod for SRL:
                      - the specified Chassis will creates a configmap and mounted as /tmp/topology.yml
                      - the specified LicSecrete reference to a secret, mounted as /opt/srlinux/etc/license.key
                      - create a PVC mount on /etc/opt/srlinux/checkpoint for persistent configuration
                    nullable: true
                    properties:
                      chassis:
                        type: string
                      image:
                        type: string
                      license:
                        type: string
                    type: object
                  srvm:
                    nullable: true
                    properties:
                      cpu:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      image:
                        type: string
                      lic:
                        type: string
                      memory:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      ports:
                        items:
                          description: |-
                            Port represents a port to expose from the virtual machine.
                            Default protocol TCP.
                            The port field is mandatory
                          properties:
                            name:
                              description: |-
                                If specified, this must be an IANA_SVC_NAME and unique within the pod. Each
                                named port in a pod must have a unique name. Name for the port that can be
                                referred to by services.
                              type: string
                            port:
                              description: |-
                                Number of port to expose for the virtual machine.
                                This must be a valid port number, 0 < x < 65536.
                              format: int32
                              type: integer
                            protocol:
                              description: |-
                                Protocol for port. Must be UDP or TCP.
                                Defaults to "TCP".
                              type: string
                          required:
                          - port
                          type: object
                        type: array
                      sysinfo:
                        type: string
                    type: object
                  vm:
                    description: GeneralVM creates a generic kubevirt VM
                    nullable: true
                    properties:
                      cpu:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      cpuPin:
                        type: boolean
                      diskSize:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      hugePage:
                        type: boolean
                      image:
                        type: string
                      init:
                        type: string
                      memory:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      passwd:
                        type: string
                      ports:
                        items:
                          description: |-
                            Port represents a port to expose from the virtual machine.
                            Default protocol TCP.
                            The port field is mandatory
                          properties:
                            name:
                              description: |-
                                If specified, this must be an IANA_SVC_NAME and unique within the pod. Each
                                named port in a pod must have a unique name. Name for the port that can be
                                referred to by services.
                              type: string
                            port:
                              description: |-
                                Number of port to expose for the virtual machine.
                                This must be a valid port number, 0 < x < 65536.
                              format: int32
                              type: integer
                            protocol:
                              description: |-
                                Protocol for port. Must be UDP or TCP.
                                Defaults to "TCP".
                              type: string
                          required:
                          - port
                          type: object
                        type: array
                      user:
                        type: string
                    type: object
                type: object
              defaultVxlanDev:
                type: string
              filePass:
                type: string
              fileSvr:
                description: SFTPSever must have format as addr/hostname:port
                type: string
              fileUser:
                type: string
              linkMTU:
                type: integer
              sideCarImage:
                type: string
              srCPMLoaderImage:
                description: this url supported by kvirt cdi, either http or docker
                  url
                type: string
              srIOMLoaderImage:
                type: string
              storageClass:
                type: string
              vxlanDevMap:
                additionalProperties:
                  type: string
                type: object
              vxlanGrp:
                type: string
            type: object
          status:
            description: status defines the observed state of KNLConfig
            properties:
              observedGeneration:
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
