name: Sidecar Container Image
on:
  push:
    tags:
      - 'sidecar[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push sidecar image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      IMG_BASE: ${{ github.repository }}/knlsidecar
      REGISTRY: ghcr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Extract Tag
        run: echo "TAG=${GITHUB_REF#refs/tags/sidecar}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      
      - name: go mod download
        run: go mod download

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image on Dockerhub
        run: make docker-push-sidecar SCIMG=${{ env.REGISTRY }}/${{ env.IMG_BASE }}:${{ env.TAG }} IMGNOTAG=${{ env.REGISTRY }}/${{ env.IMG_BASE }}
